### PR TITLE
Add Gate Operators in Readme.md

### PR DESCRIPTION
**Pull request by dotswift**
## Readme.md Update
- I was unsure if this would work with my `Liftmaster LA400UL` gate operator, because this piece of the Readme.md confused me. 
- I tested this plugin rigorously with the gate operator, and it works great. Would like to prevent other gate operator owners from getting confused. 

Thanks for making a great plugin!

### CODE REVIEW

**Comment by vfrascello** [comment]
Nice work. 
Recommend approval as this confused me for a long time. I ended up returning my gate to the manufacturer and paid a 50% restocking fee.

**Comment by pojOakland** [comment]
> Nice work. 
> Recommend approval as this confused me for a long time. I ended up returning my gate to the manufacturer and paid a 50% restocking fee. 

I did the same thing!  Comforting to see both someone willing to clarify this.

**Comment by vfrascello** [comment]
Can this please be merged. I just reorddered my gate

**Comment by jarz** [comment]
> Can this please be merged. I just reorddered my gate

It's just a documentation change. The gate will work with the current plugin.

**Pull request closed without merging**
